# -*- coding: utf-8 -*-
"""Omar - Github repo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PNi7pCNEOV6KUylmLp9z5ZYShnRccjid
"""

import torch
import torchvision
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.utils.data as data


import torchvision.datasets as datasets
import torchvision.models as models
import torchvision.transforms as transforms

from sklearn import decomposition
from sklearn import manifold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay
from tqdm.notebook import tqdm, trange


from torchvision.models import ResNet18_Weights

from typing import Tuple
from PIL import Image
from pathlib import Path
import pathlib
import os
import copy

import matplotlib.pyplot as plt
import numpy as np
import pandas


import random
import time

SEED = 1922

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed(SEED)
torch.backends.cudnn.deterministic = True

class CXRData(data.Dataset):

    def __init__(self, targ_dir: str, transform=None) :


        self.paths = []
        for pattern in ["*/*.jpg", "*/*.jpeg", "*/*.png", "*/*.JPG", "*/*.JPEG", "*/*.PNG"]:

              self.paths.extend(pathlib.Path(targ_dir).glob(pattern))

        self.transform = transform

        self.classes = sorted([item.name for item in pathlib.Path(targ_dir).iterdir() if item.is_dir()])

        self.class_to_idx = {class_name: i for i, class_name in enumerate(self.classes)}


    def load_image(self, index: int) :

        image_path = self.paths[index]
        return Image.open(image_path).convert("RGB")

    def __len__(self) :
        "Returns the total number of samples."
        return len(self.paths)

    def __getitem__(self, index: int) -> Tuple[torch.Tensor, int]:
        img = self.load_image(index)
        class_name = self.paths[index].parent.name
        class_idx = self.class_to_idx[class_name]

        if self.transform is not None:
          img = self.transform(img)

        return img, class_idx

data_dir = Path("path/to/chest_xray")
train_dir = data_dir / "train"
test_dir = data_dir / "test"

mean = [0.485, 0.456, 0.406]
std = [0.229, 0.224, 0.225]

print(f'Calculated mean: {mean}')
print(f'Calculated std: {std}')

train_transforms = transforms.Compose([
                            transforms.RandomRotation(5, fill=(0,)),
                            transforms.RandomCrop(100, padding=2),
                            transforms.ToTensor(),
                            transforms.Normalize(mean=mean, std=std)
                                      ])

test_transforms = transforms.Compose([
    transforms.Resize((100, 100)),
    transforms.ToTensor(),
    transforms.Normalize(mean=mean, std=std)
])

train_data = CXRData(train_dir, transform=train_transforms)

test_data = CXRData(test_dir, transform=test_transforms)

VALID_RATIO = 0.8

n_train_examples = int(len(train_data) * VALID_RATIO)
n_valid_examples = len(train_data) - n_train_examples

train_data, valid_data = data.random_split(train_data,
                                           [n_train_examples, n_valid_examples])

valid_data = copy.deepcopy(valid_data)
valid_data.dataset.transform = test_transforms

print(f'Number of training examples: {len(train_data)}')
print(f'Number of validation examples: {len(valid_data)}')
print(f'Number of testing examples: {len(test_data)}')

BATCH_SIZE = 32
NUM_WORKERS = 4

train_iterator = data.DataLoader(train_data,
                                 shuffle=True,
                                 batch_size=BATCH_SIZE, num_workers=NUM_WORKERS)

valid_iterator = data.DataLoader(valid_data,
                                 batch_size=BATCH_SIZE, num_workers=NUM_WORKERS)

test_iterator = data.DataLoader(test_data,
                                batch_size=BATCH_SIZE, num_workers=NUM_WORKERS)

def calculate_accuracy(y_pred, y):
    top_pred = y_pred.argmax(1, keepdim=True)
    correct = top_pred.eq(y.view_as(top_pred)).sum()
    acc = correct.float() / y.shape[0]
    return acc

def train(model, iterator, optimizer, criterion, device):

    epoch_loss = 0
    epoch_acc = 0


    for (x, y) in tqdm(iterator, desc="Training", leave=False):

        x = x.to(device)
        y = y.to(device)

        optimizer.zero_grad()

        y_pred = model(x)

        loss = criterion(y_pred, y)

        acc = calculate_accuracy(y_pred, y)

        loss.backward()

        optimizer.step()

        epoch_loss += loss.item()
        epoch_acc += acc.item()

    return epoch_loss / len(iterator), epoch_acc / len(iterator)

model = torchvision.models.resnet18(weights=ResNet18_Weights.DEFAULT)
    model.train()
    model.fc = nn.Linear(model.fc.in_features, 2)
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = model.to(device)
    optimizer = optim.Adam(model.parameters(), lr = 1e-4)
    criterion = nn.CrossEntropyLoss()

def test(model, iterator, criterion, device):

    epoch_loss = 0
    epoch_acc = 0

    model.eval()

    with torch.no_grad():

        for (x, y) in tqdm(iterator, desc="Evaluating", leave=False):

            x = x.to(device)
            y = y.to(device)

            y_pred = model(x)

            loss = criterion(y_pred, y)

            acc = calculate_accuracy(y_pred, y)

            epoch_loss += loss.item()
            epoch_acc += acc.item()

    return epoch_loss / len(iterator), epoch_acc / len(iterator)

def epoch_time(start_time, end_time):
    elapsed_time = end_time - start_time
    elapsed_mins = int(elapsed_time / 60)
    elapsed_secs = int(elapsed_time - (elapsed_mins * 60))
    return elapsed_mins, elapsed_secs

EPOCHS = 50
patience = 5
epochs_without_improvement = 0

best_valid_loss = float('inf')

for epoch in trange(EPOCHS, desc="Epochs"):

    start_time = time.monotonic()

    train_loss, train_acc = train(model, train_iterator, optimizer, criterion, device)
    valid_loss, valid_acc = test(model, valid_iterator, criterion, device)

    if valid_loss < best_valid_loss:
        best_valid_loss = valid_loss
        epochs_without_improvement = 0
        torch.save(model.state_dict(), 'tut2-model.pt')
    else:
        epochs_without_improvement += 1
        if epochs_without_improvement >= patience:
            print(f'Early stopping after {epoch} epochs.')
            break


    end_time = time.monotonic()

    epoch_mins, epoch_secs = epoch_time(start_time, end_time)

    print(f'Epoch: {epoch+1:02} | Epoch Time: {epoch_mins}m {epoch_secs}s')
    print(f'\tTrain Loss: {train_loss:.3f} | Train Acc: {train_acc*100:.2f}%')
    print(f'\t Val. Loss: {valid_loss:.3f} |  Val. Acc: {valid_acc*100:.2f}%')

